/*
 * Copyright 2025 Clidey, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ImageGrid: typeof import('./components/ImageGrid.vue')['default']
    ImageGridSkeleton: typeof import('./components/ImageGridSkeleton.vue')['default']
    Main: typeof import('./components/Main.vue')['default']
    MediaOverlay: typeof import('./components/MediaOverlay.vue')['default']
    NSFWAlert: typeof import('./components/NSFWAlert.vue')['default']
    ProxyPromptDialog: typeof import('./components/ProxyPromptDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollContent: typeof import('./components/ScrollContent.vue')['default']
    SearchBar: typeof import('./components/SearchBar.vue')['default']
    SettingsDialog: typeof import('./components/SettingsDialog.vue')['default']
  }
}
